on:
  push:
    branches:
      - main
name: "Build & Release"
jobs:
  build:
    name: "Build & Release"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.18.7'
      - run: flutter pub get
      - run: flutter build appbundle --debug
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
